### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by progfolio** [tecosaur/orgwebsite#2]
Currently the top of each image is slightly above the top of it's description. Aligning these should create a cleaner grid.

**Comment by tecosaur** [comment]
Ah yes! Thanks for spotting that.

**Comment by progfolio** [comment]
Looks pretty good now! The only thing is the svg under the "Extensibility" section doesn't quite line up visually. The SVG itself has a border. Cropping it a little tighter to the content might work better.

Nice work, overall, by the way! This is something that I think is long overdue for Org mode.

**Comment by tecosaur** [comment]
Cropped! :smiley: 

Thanks for the kind words. After becoming enraptured by org-mode, I've felt like the website, unfortunately, does org a bit of a disservice — particularly in terms of first impressions for people who are hearing about org for the first time.
Hopefully, this little redesign will be able to help it this regard :grin:

If you have any thoughts on what to do with the home page, I'd be quite interested in hearing them - I'm still mulling over possible approaches but haven't been able to work out any content yet.

**Comment by progfolio** [comment]
> I've felt like the website, unfortunately, does org a bit of a disservice

Agreed. It deserves the same attention to detail the software itself receives. Glad you're taking it on.

> If you have any thoughts on what to do with the home page, I'd be quite interested in hearing them - I'm still mulling over possible approaches but haven't been able to work out any content yet.

I will take some notes on the site as a whole over the next couple days and make a general issue to share them.

**Comment by tecosaur** [comment]
> I will take some notes on the site as a  whole over the next couple days and make a general issue to share them.

Thank you for taking me up on this. Much obliged ☺️

Oh, it's probably worth noting that the only other functional page at the moment is "Install". Just FYI.

**Comment by tecosaur** [comment]
Hello again,

I just want to quickly note that there are now two more pages: [Quickstart](http://orgmode.tecosaur.com/quickstart.html) and [Contribute](http://orgmode.tecosaur.com/contribute.html) :smiley:

**Comment by progfolio** [comment]
May want to go with the lower case versions of the metadata keywords, e.g. `#+title`.
I think (could be wrong) this is the default in the latest Org.

**Comment by progfolio** [comment]
Probably worth linking to the new https://orgmode.org/list/ from the Contribute page, too.

**Comment by tecosaur** [comment]
I haven't been able to conclusively tell whether org keys should be in upper or lower case - if you have any helpful links on that front that wound be great. Changed the list link :)

**Comment by progfolio** [comment]
Here's a thread where it was discussed recently which also links to previous discussions:
https://orgmode.org/list/CAELgYhf-4UsEQy2C2j1ROfSSkUw7yzO5gvFWyCgQAOXUK5xYjg@mail.gmail.com/

**Comment by tecosaur** [comment]
Thanks

**Comment by tecosaur** [comment]
Oh, I've also redone the favicon, FYI : removed the horn for small sizes (16-32px), and added extra formats (see https://realfavicongenerator.net/favicon_checker?protocol=http&site=orgmode.tecosaur.com%2F )

Just keeping you up to date :stuck_out_tongue:

**Comment by tecosaur** [comment]
Now with a fancy home page :partying_face:

**Comment by progfolio** [comment]
Instead of making a new issue, I'll just rename this one.
Here's some notes for a few of the pages:

# Home

-   s/to-do Lists/to-do lists/
-   "plain-text" or "plain text"? Should be consistent in copy.

> Org is a highly flexible <span class="underline">structured</span> plain text file format, <span class="underline">composed of</span> a few **simple, yet** versatile, <span class="underline">structures</span>.
> 
> It is constructed to be **simple** enough for the novice, **yet** powerful enough for the expert.

The first sentence mentions that the structured format twice and the second is communicating a similar idea.
Perhaps rewording them as a single sentence would be stronger.

> To read a bit more about Org, other than the quickstart and manual, there’s also a guide, and Worg is a wealth of community-written docs.

Maybe a shorter sentence with a list of links would be clearer here. e.g.

> Read more about Org:
> 
> -   quickstart guide
> -   manual
> -   guide
> -   Worg community docs

> Once you’ve used Org for a bit, you’ll know it’s great — but did you know it’s so great that there have been (scientific) papers written about the value of Org for reproducible research.

This is phrased as a question, but ends with a period. I think it would actually be better to phrase it as a statement instead of a "but did you know?". This may also fit in better with the first paragraph.
Give an example of novice use and contrast it with the reproducible research example.


<a id="orgfc423f6"></a>

# Features

-   The h2 headings seem like they're not actually textually centered. e.g.

For "Tables", the "T" is at the center of the screen (so the heading looks like it's hanging out to the right)
Would look more balanced if the text was centered.


<a id="org3cd748b"></a>

# Tools

-   Navbar blocking content, needs padding at top.

**Comment by tecosaur** [comment]
# Home

-   [X] s/to-do Lists/to-do lists/
-   [X] &ldquo;plain-text&rdquo; or &ldquo;plain text&rdquo;? Should be consistent in copy.

- Sentence reworded to:

> Org is a highly flexible structured plain text file format, composed of a few simple, yet versatile, structures — constructed to be both simple enough for the novice and powerful enough for the expert.

- Maybe a shorter sentence with a list of links would be clearer here.

I only want to draw attention to the last two links though, since the first two are explicitly mentioned before. A minor re-write though:

> As well at the quickstart and manual, there’s also a guide, and a wealth of community-written docs on Worg .

- Papers rewrite:

> Once you’ve used Org for a bit, you’ll know it’s great — it’s actually so great that there have been (scientific) papers written about the value of Org for reproducible research.

# Features

-   [X] The h2 headings seem like they&rsquo;re not actually textually centered. e.g.

# Tools

-   [X] Navbar blocking content, needs padding at top.

**Comment by tecosaur** [comment]
We're getting close to publishing, and everything here is resolved so I'll close this issue :)
